name: Generate Real Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  snake:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Generate REAL snake animation
        uses: phosphoer/snk-animated@v1
        with:
          github_user_name: Arav-Arun
          output_path: dist/real-snake.svg
          snake_color: "#00ff6e"
          snake_head_color: "#1affb5"
          background_color: "#0d1117" # GitHub dark mode background
          fps: 12

      - name: Publish to output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: dist
